cquest:
	@echo ""
	@echo "Please 'git checkout patches' before trying to 'make'!"
	@echo ""
	@echo "Or, 'git checkout patches -- Makefile' if you want to try"
	@echo "compiling the original code (which is expected to fail)."
	@echo ""

.PHONY: cquest
